#!/usr/bin/env python3
"""
build_h2h.py — Aggregate head-to-head records from cached past-matches files.

Pure Python, no API calls. Reads everything in scripts/cache/api/ and emits
data/h2h.js consumed by the matchup predictor.

USAGE
-----
    python3 scripts/build_h2h.py

OUTPUT
------
    data/h2h.js (replaces hardcoded WTA_H2H + ATP_H2H lookup tables)

Schema:
    H2H = {
      atp: {
        "<bioA>-<bioB>": {
          aW: 6, bW: 4,
          s: { H: "4-3", C: "1-1", G: "1-0" },
          rec: [2,1,2,1,2],          // last 5 results from A's perspective (1=W, 2=L)
          last: "2026-04-25"
        }
      },
      wta: { ... }
    }
"""
import json, re, sys, glob
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CACHE_DIR = REPO_ROOT / "scripts" / "cache" / "api"
OUT_FILE  = REPO_ROOT / "data" / "h2h.js"


def load_mid_to_bio(tour: str) -> dict:
    """{matchstat_id: bio.id} for bios with a mid set."""
    text = (REPO_ROOT / "data" / f"players_{tour}.js").read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r"\{id:(\d+),\s*mid:(\d+)", text):
        out[int(m.group(2))] = int(m.group(1))
    return out


def surface_from_court(court_id: int | None) -> str:
    """Matchstat court ids: 1=hard indoor, 2=hard outdoor, 3=clay, 5=grass, etc.
    Conservative mapping; defaults to 'H' for unknowns."""
    if court_id in (3,):     return "C"
    if court_id in (5,):     return "G"
    if court_id in (4,):     return "C"   # clay variant
    return "H"


def aggregate_for_tour(tour: str, mid_to_bio: dict) -> dict:
    """Walk every cached past-matches file for `tour`, build per-pair H2H."""
    pair_stats = defaultdict(lambda: {
        "aW": 0, "bW": 0,
        "s": defaultdict(lambda: [0, 0]),  # surf -> [aW, bW]
        "matches": [],                     # for "rec" + "last"
    })

    pat = str(CACHE_DIR / f"{tour}_player_past-matches_*.json")
    files = sorted(glob.glob(pat))

    seen_match_ids = set()  # dedupe — same match appears in both players' files

    for f in files:
        try:
            data = json.load(open(f))
        except Exception:
            continue
        rows = data.get("data") or data
        if not isinstance(rows, list):
            continue

        for m in rows:
            mid_match = m.get("id")
            if mid_match in seen_match_ids:
                continue
            seen_match_ids.add(mid_match)

            p1 = m.get("player1Id"); p2 = m.get("player2Id")
            winner = m.get("match_winner") or m.get("winnerId")
            if not (p1 and p2 and winner): continue
            bio1 = mid_to_bio.get(p1); bio2 = mid_to_bio.get(p2)
            if not (bio1 and bio2): continue   # only count when BOTH are bios we track

            # Canonicalize pair as low-bio-id first
            a, b = (bio1, bio2) if bio1 < bio2 else (bio2, bio1)
            a_won = (winner == p1 and bio1 == a) or (winner == p2 and bio2 == a)
            key = f"{a}-{b}"
            stats = pair_stats[key]
            if a_won: stats["aW"] += 1
            else:     stats["bW"] += 1

            tour_obj = m.get("tournament") or {}
            surf = surface_from_court(tour_obj.get("courtId"))
            stats["s"][surf][0 if a_won else 1] += 1

            date = (m.get("date") or "")[:10]
            stats["matches"].append((date, 1 if a_won else 2))

    # Build output dict — drop pairs with 0 matches, sort recent
    out = {}
    for key, s in pair_stats.items():
        if s["aW"] + s["bW"] == 0: continue
        s["matches"].sort()
        last = s["matches"][-1][0] if s["matches"] else ""
        rec = [r[1] for r in s["matches"][-5:]]
        # Format surface dict as "aW-bW" strings
        surf_fmt = {sk: f"{v[0]}-{v[1]}" for sk, v in s["s"].items()}
        out[key] = {
            "aW":  s["aW"],
            "bW":  s["bW"],
            "s":   surf_fmt,
            "rec": rec,
            "last": last,
        }
    return out


def main():
    print("Building H2H from cached past-matches files...")
    atp_h2h = aggregate_for_tour("atp", load_mid_to_bio("atp"))
    wta_h2h = aggregate_for_tour("wta", load_mid_to_bio("wta"))
    print(f"  ATP pairs: {len(atp_h2h)}")
    print(f"  WTA pairs: {len(wta_h2h)}")

    js = (
        "/**\n"
        " * h2h.js — AUTO-GENERATED by scripts/build_h2h.py\n"
        " * Aggregated from cached Matchstat past-matches files.\n"
        " *\n"
        " * Schema: keyed by tour, then by 'bioA-bioB' (sorted, low first).\n"
        " *   aW/bW   = wins for each side\n"
        " *   s       = per-surface 'aW-bW' strings (H/C/G)\n"
        " *   rec     = last 5 match outcomes from A's POV (1=W, 2=L)\n"
        " *   last    = date of most recent meeting\n"
        " */\n"
        f"const H2H = {json.dumps({'atp': atp_h2h, 'wta': wta_h2h}, separators=(',',':'))};\n"
    )
    OUT_FILE.write_text(js, encoding="utf-8")
    print(f"✓ Wrote {OUT_FILE.relative_to(REPO_ROOT)} ({len(js):,} chars)")


if __name__ == "__main__":
    main()
