#!/usr/bin/env python3
"""
export_for_d1.py — Generate D1-compatible SQL from the local SQLite DB.

D1 (SQLite at the edge) accepts standard SQLite SQL but rejects a few
SQLite-specific statements that `sqlite3 .dump` includes (PRAGMA, BEGIN
TRANSACTION, COMMIT, sqlite_master, sqlite_sequence). This script emits
INSERT-only SQL stripped of those, chunked into files small enough for
`wrangler d1 execute --file=` to handle.

USAGE
-----
    # On Connor's Mac (where data/tennis.db exists):
    python3 scripts/export_for_d1.py
    # Outputs:
    #   workers/seed/01_players.sql
    #   workers/seed/02_tournaments.sql
    #   workers/seed/03_matches.sql
    #   workers/seed/04_rankings.sql

    # Apply each in order:
    for f in workers/seed/*.sql; do
        wrangler d1 execute tennis --remote --file="$f"
    done
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from db import connect, REPO_ROOT


SEED_DIR = REPO_ROOT / "workers" / "seed"
# D1 size limit per `execute --file` is generous (~50MB) but multi-MB requests
# are slow. Keep each chunk to ~1MB / ~2000 statements for fast iteration.
CHUNK_BYTES = 1_000_000


def _q(v) -> str:
    """Format a Python value as a SQL literal (D1-compatible)."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    # Strings: escape single quotes by doubling.
    s = str(v).replace("'", "''")
    return f"'{s}'"


def export_table(conn, table: str, columns: list[str]) -> list[str]:
    """Return list of INSERT statements for a table."""
    cols = ", ".join(columns)
    out: list[str] = []
    for row in conn.execute(f"SELECT {cols} FROM {table}"):
        vals = ", ".join(_q(row[c]) for c in columns)
        out.append(f"INSERT OR REPLACE INTO {table} ({cols}) VALUES ({vals});")
    return out


def write_chunked(stmts: list[str], path_prefix: Path, max_bytes: int = CHUNK_BYTES) -> int:
    """Write `stmts` into one or more files at path_prefix-NNN.sql, each
    capped at max_bytes. Returns the file count."""
    SEED_DIR.mkdir(parents=True, exist_ok=True)
    chunks = []
    cur: list[str] = []
    cur_size = 0
    for s in stmts:
        size = len(s) + 1
        if cur_size + size > max_bytes and cur:
            chunks.append(cur)
            cur = []
            cur_size = 0
        cur.append(s)
        cur_size += size
    if cur:
        chunks.append(cur)

    for i, chunk in enumerate(chunks, 1):
        suffix = f"_{i:02d}" if len(chunks) > 1 else ""
        out = path_prefix.with_name(path_prefix.name + suffix + ".sql")
        out.write_text("\n".join(chunk) + "\n", encoding="utf-8")
    return len(chunks)


def main() -> int:
    conn = connect(read_only=True)

    PLAYERS_COLS = ["mid", "tour", "bio_id", "sid", "name", "ab", "country", "age", "meta"]
    TOURNAMENTS_COLS = ["id", "name", "short", "tour", "type", "surface", "draw_size",
                        "start_date", "end_date", "api_id_atp", "api_id_wta", "active",
                        "points_table"]
    MATCHES_COLS = ["id", "tournament_id", "tournament_api_id", "tournament_name",
                    "date", "round", "surface", "tour", "p1_id", "p2_id", "winner_id",
                    "score", "best_of", "stat_p1", "stat_p2", "fetched_at", "raw"]
    RANKINGS_COLS = ["tour", "snapshot_date", "bio_id", "rank", "pts", "ytd_pts"]

    plan = [
        ("01_players",     "players",            PLAYERS_COLS),
        ("02_tournaments", "tournaments",        TOURNAMENTS_COLS),
        ("03_matches",     "matches",            MATCHES_COLS),
        ("04_rankings",    "rankings_snapshots", RANKINGS_COLS),
    ]

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    # Wipe any prior chunks so a re-run doesn't leave stale `_02.sql` files
    # when a later run produces fewer chunks.
    for f in SEED_DIR.glob("*.sql"):
        f.unlink()

    total_files = 0
    total_rows = 0
    print(f"[export-d1] writing to {SEED_DIR.relative_to(REPO_ROOT)}/")
    for prefix, table, cols in plan:
        stmts = export_table(conn, table, cols)
        n_files = write_chunked(stmts, SEED_DIR / prefix)
        total_files += n_files
        total_rows  += len(stmts)
        print(f"  {table:<22} {len(stmts):>6} rows → {n_files} file(s)")

    # Manifest with a runner one-liner.
    manifest = SEED_DIR / "README.md"
    manifest.write_text(
        f"# D1 seed files\n\n"
        f"Generated by `scripts/export_for_d1.py` from `data/tennis.db`.\n"
        f"Total: {total_rows:,} rows across {total_files} file(s).\n\n"
        f"Apply (in lexical order — file prefixes enforce dependency order):\n\n"
        f"```bash\n"
        f"for f in workers/seed/*.sql; do\n"
        f'    echo "→ $f"\n'
        f'    wrangler d1 execute tennis --remote --file="$f"\n'
        f"done\n"
        f"```\n\n"
        f"Re-running this script overwrites every file in this directory.\n"
    )
    print(f"\n[export-d1] {total_rows:,} rows total across {total_files} files")
    print(f"[export-d1] see {manifest.relative_to(REPO_ROOT)} for runner")
    return 0


if __name__ == "__main__":
    sys.exit(main())
